### ISSUE TITLE
wildcard-match bug

### ISSUE THREAD

**Issue by itadapter** [saleyn/utxx#12]
utxx/src/string.cpp
string pattern matching,
should wrap inner loop in outer loop to handle this case:

"heloo address address Address Address address"   should match on '*address'

**Comment by saleyn** [comment]
Added this test case, yet the algorithm does match on it correctly:
https://github.com/saleyn/utxx/blob/master/test/test_string.cpp#L193

**Comment by itadapter** [comment]
yes it works because it relies on /0x00 char behavior  - it treats it as a valid char not equal to any other
for efficiency and brevity it makes sense, readability - maybe add a comment that explains how input gets exhausted against /0x00

**Comment by saleyn** [comment]
I merged the first loop into the second one and added comments for clarity.
